/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

export interface Event {
  createdBy?: string;
  createdDate?: string;
  date?: string;
  groupId?: number;
  id?: number;
  updatedBy?: string;
  updatedDate?: string;
}
