/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

import { Group } from "./group";
import { Team } from "./team";

export interface Event {
  createdBy?: string;
  createdDate?: string;
  date?: Date;
  groupId?: number;
  id?: number;
  updatedBy?: string;
  updatedDate?: Date;
  teams?: Team[];
  group?: Group
}