/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

import { Group } from "./group";
import { User } from "./user";

export interface GroupMember {
  confirmed: number;
  createdBy?: string;
  createdDate?: string;
  groupId?: number;
  id?: number;
  position?: string | null;
  updatedBy?: string;
  updatedDate?: string;
  userId?: number;
  user?: User;
  group?: Group;
}

// 'deciding' -> 0
// 'absent' -> 1
// 'confirmed' -> 2