/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

import { Event } from "./event";
import { GroupMember } from "./groupMember";
import { Location } from "./location";
import { User } from "./user";

export interface Group {
  description?: string;
  adminId?: number;
  createdBy?: string;
  createdDate?: string;
  id?: number;
  isPublic?: boolean;
  level?: number;
  locationId?: number;
  name?: string | null;
  updatedBy?: string;
  updatedDate?: string;
  admin?: User;
  location?: Location;
  groupMembers?: GroupMember[];
  events?: Event[];
}
