/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

export interface Group {
  adminId?: number;
  createdBy?: string;
  createdDate?: string;
  id?: number;
  isPublic?: boolean;
  /** @nullable */
  level?: string | null;
  locationId?: number;
  /** @nullable */
  name?: string | null;
  updatedBy?: string;
  updatedDate?: string;
}
