/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

export interface GroupMember {
  /** @nullable */
  confirmed?: string | null;
  createdBy?: string;
  createdDate?: string;
  groupId?: number;
  id?: number;
  /** @nullable */
  position?: string | null;
  updatedBy?: string;
  updatedDate?: string;
  userId?: number;
}
