/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

import { Group } from "./group";

export interface Location {
  createdBy?: string;
  createdDate?: string;
  id?: number;
  latitude?: number;
  longitude?: number;
  updatedBy?: string;
  updatedDate?: string;
  groups?: Group[];
  streetNumber?: string;
  street?: string;
  neighborhood?: string;
  city?: string;
  country?: string;
  state?: string;
  coordsMatch?: boolean;
}
