/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

import { Team } from "./team";

export interface Match {
  createdBy?: string;
  createdDate?: string;
  duration?: number;
  id?: number;
  teamOneId?: number;
  teamTwoId?: number;
  updatedBy?: string;
  updatedDate?: string;
  teamOne?: Team;
  teamTwo?: Team;
}
