/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

import { GroupMember } from "./groupMember";
import { Score } from "./score";
import { Team } from "./team";

export interface Player {
  id?: number;
  position?: string | null;
  groupMemberId?: number;
  groupMember?: GroupMember;
  teamId?: number;
  team?: Team;
  eventId?: number;
  event?: Event;
  scores?: Score[];
}
