/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

export interface Player {
  createdBy?: string;
  createdDate?: string;
  groupMemberId?: number;
  id?: number;
  /** @nullable */
  position?: string | null;
  teamId?: number;
  updatedBy?: string;
  updatedDate?: string;
}
