/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

export interface Score {
  assistances?: number;
  blocks?: number;
  createdBy?: string;
  createdDate?: string;
  fouls?: number;
  id?: number;
  matchId?: number;
  onePoint?: number;
  playerId?: number;
  rebounds?: number;
  steals?: number;
  threePoints?: number;
  turnOvers?: number;
  twoPoints?: number;
  updatedBy?: string;
  updatedDate?: string;
}
