/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

export interface Team {
  createdBy?: string;
  createdDate?: string;
  eventId?: number;
  id?: number;
  /** @nullable */
  teamName?: string | null;
  updatedBy?: string;
  updatedDate?: string;
}
