/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

import { Event } from "./event";
import { Match } from "./match";
import { Player } from "./player";

export interface Team {
  id?: number;
  teamName?: string | null;
  eventId?: number;
  event?: Event;
  players?: Player[];
}
