/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

import { GroupMember } from "./groupMember";

export interface User {
  birthDate?: string;
  createdBy?: string;
  createdDate?: string;
  email?: string;
  height?: number;
  id?: number;
  name?: string;
  password?: string;
  confirmPassword?: string;
  position?: string | null;
  surname?: string;
  updatedBy?: string;
  updatedDate?: string;
  groupMembers?: GroupMember[];
}
