/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BrasqueteBackEnd
 * OpenAPI spec version: 1.0
 */

export interface User {
  birthDate?: string;
  createdBy?: string;
  createdDate?: string;
  /** @minLength 1 */
  email: string;
  emailConfirmed?: boolean;
  height?: number;
  id?: number;
  name: number;
  /** @minLength 1 */
  password: string;
  /** @nullable */
  position?: string | null;
  surname: number;
  updatedBy?: string;
  updatedDate?: string;
}
