name: "Build Android"

on:
  push:
    branches:
      - build
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v4

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
          
      - name: Install dependencies
        run: |
          npm install -g expo-cli eas-cli
          npm install

      - name: Build APK
        run: |
          eas build --platform android --profile development --local --non-interactive --output ${{ github.workspace }}/app-release.apk
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_PUBLIC_MAPS_API_KEY_DEV: ${{ secrets.EXPO_PUBLIC_MAPS_API_KEY_DEV }}
          EXPO_PUBLIC_MAPS_API_KEY_PRD: ${{ secrets.EXPO_PUBLIC_MAPS_API_KEY_PRD }}
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.apk
