name: "Build Android"

on:
  push:
    branches:
      - build
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v2

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g expo-cli eas-cli
          npm install

      - name: Build APK
        run: |
          EXPO_TOKEN=${{ secrets.EXPO_TOKEN }} expo build:android -t apk --no-wait --non-interactive
